### ISSUE TITLE
lateral-nav-menu

### ISSUE THREAD

**Issue by bgdaniels** [marcoscv-work/experimental-liferay-themes#2]
Hi, I've been trying to figure out how to remove hamburger icon and just have the vertical menu showing all the time. Have not been successful :-(  If you don't mind, how can I remove the icon and just have a vertical menu?

thanks

**Comment by marcoscv-work** [comment]
do you want to have the vertical menu always oppened?

**Comment by bgdaniels** [comment]
yes, that is what I meant. Did not express myself well :-(

Also, I just want to say how fortunate Liferay is having someone as talented as you.

**Comment by marcoscv-work** [comment]
thanks you @bgdaniels !
No worries, I'll try to do it as soon as possible. I will keep this issue opened, like a remember to provide you a solution, although this is not issue ;) !

**Comment by bgdaniels** [comment]
I know this not an issue, just did not know where to post a comment :-) . I didn't mean for you to code something. I thought it might be simple but not being a developer, I was struggling trying to figure it out.

thank you

**Comment by marcoscv-work** [comment]
Hey @bgdaniels I've just created a new brunch:

https://github.com/marcoscv-work/experimental-liferay-themes/tree/vertical-dockbar-fixed

There you have a new commit with all changes I think you need.
https://github.com/marcoscv-work/experimental-liferay-themes/commit/150bbbca024c4c0518db2fa7529088965dc5db6e

Regards!
